In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import sklearn as sfrom collections import Counter
from sklearn.model_selection import train_test_split
from imblearn.under_sampling import RandomUnderSampler

In [2]:
# !pip install -U imbalanced-learn

In [6]:
df = pd.read_csv('./data/df_clean.csv')

In [7]:
df.head()

,swab_type,covid19_test_results,age,high_risk_exposure_occupation,diabetes,chd,htn,cancer,asthma,copd,...,ctab_nan,labored_respiration_False,labored_respiration_True,labored_respiration_nan,rhonchi_False,rhonchi_True,rhonchi_nan,wheezes_False,wheezes_True,wheezes_nan
0,0,0,15,False,False,False,False,False,False,False,...,0,1,0,0,1,0,0,1,0,0
1,1,0,20,False,False,False,False,False,False,False,...,0,1,0,0,0,1,0,0,1,0
2,0,0,14,False,False,False,False,False,False,False,...,0,1,0,0,0,0,1,0,0,1
3,1,0,32,False,False,False,False,False,False,False,...,0,0,0,1,0,0,1,0,0,1
4,0,0,29,False,False,False,False,False,False,False,...,0,0,0,1,0,0,1,1,0,0